// <auto-generated />
using System;
using DodoBed.Manufacturing.SqlPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DodoBed.Manufacturing.SqlPersistence.Migrations
{
    [DbContext(typeof(DodoBedManufacturingContext))]
    [Migration("20210909170826_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("ContactId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.Contact", b =>
                {
                    b.Property<long>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SupplierId")
                        .HasColumnType("bigint");

                    b.HasKey("ContactId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.DigitalAddress", b =>
                {
                    b.Property<int>("DigitalAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DigitalAddressTypeId")
                        .HasColumnType("int");

                    b.HasKey("DigitalAddressId");

                    b.HasIndex("ContactId");

                    b.HasIndex("DigitalAddressTypeId");

                    b.ToTable("DigitalAddresses");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.DigitalAddressType", b =>
                {
                    b.Property<int>("DigitalAddressTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DigitalAddressTypeId");

                    b.ToTable("DigitalAddressTypes");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.Dimension", b =>
                {
                    b.Property<int>("DimensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("DimensionId");

                    b.ToTable("Dimensions");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.Product", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 9, 9, 13, 8, 25, 587, DateTimeKind.Local).AddTicks(2229));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DimensionId")
                        .HasColumnType("int");

                    b.Property<string>("InHouseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 9, 9, 13, 8, 25, 603, DateTimeKind.Local).AddTicks(9603));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.HasIndex("DimensionId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.ProductLocation", b =>
                {
                    b.Property<int>("ProductLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AisleNumber")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BuildingNumber")
                        .HasColumnType("int");

                    b.Property<long?>("ProductItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("SectionNumber")
                        .HasColumnType("int");

                    b.Property<int>("ShelfNumber")
                        .HasColumnType("int");

                    b.HasKey("ProductLocationId");

                    b.HasIndex("ProductItemId");

                    b.ToTable("ProductLocations");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.Supplier", b =>
                {
                    b.Property<long>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.Tool", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 9, 9, 13, 8, 25, 613, DateTimeKind.Local).AddTicks(1634));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 9, 9, 13, 8, 25, 613, DateTimeKind.Local).AddTicks(3368));

                    b.Property<string>("ManufacturerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.Address", b =>
                {
                    b.HasOne("DodoBed.Manufacturing.Domain.Entities.Contact", null)
                        .WithMany("ContactAddresses")
                        .HasForeignKey("ContactId");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.Contact", b =>
                {
                    b.HasOne("DodoBed.Manufacturing.Domain.Entities.Supplier", null)
                        .WithMany("Contacts")
                        .HasForeignKey("SupplierId");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.DigitalAddress", b =>
                {
                    b.HasOne("DodoBed.Manufacturing.Domain.Entities.Contact", null)
                        .WithMany("DigitalAddresses")
                        .HasForeignKey("ContactId");

                    b.HasOne("DodoBed.Manufacturing.Domain.Entities.DigitalAddressType", "DigitalAddressType")
                        .WithMany()
                        .HasForeignKey("DigitalAddressTypeId");

                    b.Navigation("DigitalAddressType");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.Product", b =>
                {
                    b.HasOne("DodoBed.Manufacturing.Domain.Entities.Dimension", "Dimension")
                        .WithMany()
                        .HasForeignKey("DimensionId");

                    b.Navigation("Dimension");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.ProductLocation", b =>
                {
                    b.HasOne("DodoBed.Manufacturing.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductItemId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.Contact", b =>
                {
                    b.Navigation("ContactAddresses");

                    b.Navigation("DigitalAddresses");
                });

            modelBuilder.Entity("DodoBed.Manufacturing.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
